version: "2"

services:
  web:
    links:
      - db:db
    build:
      context: ./docker
      dockerfile: base-app-image.yml
    environment:
      - NODE_ENV=development
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: node vanilla-server.js
  db:
    image: fliuheyan/mysql-5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
